hrrrmm

diff --git a/guest/linux-6.11/rootfs/init b/guest/linux-6.11/rootfs/init
--- a/guest/linux-6.11/rootfs/init
+++ b/guest/linux-6.11/rootfs/init
@@ -11,8 +11,6 @@ TARGET_DEV=${mountq_target:-/dev/vda}
 FALLBACK_DEV=${mountq_fallback:-/dev/sr0}
 MOUNT_POINT=/mnt
 PORT_PATH=/dev/vport0p1
-export MOUNT_POINT
-export PORT_PATH
 
 mount -t devtmpfs devtmpfs /dev
 mount -t proc none /proc
@@ -45,17 +43,20 @@ else
   MOUNT_SUCCESS=0
 fi
 
-export MOUNT_SUCCESS
+export MOUNT_SUCCESS="$MOUNT_SUCCESS"
+export MOUNT_POINT="$MOUNT_POINT"
+export PORT_PATH="$PORT_PATH"
 
 MODE=$(sed -n 's/.*mode=\([^ ]*\).*/\1/p' /proc/cmdline)
 SCRIPT="/init.${MODE:-sh}" 
 
+echo "root:password" | chpasswd
+
 echo "[INIT] Dispatching to: $SCRIPT"
-"$SCRIPT"
+"$SCRIPT" || echo "Failed" "$?"
 
 /bin/sh
 
 # keep trying every way we can to stop this from spinlocking
-on_exit
-poweroff -f
+poweroff -f &
 sleep infinity
